version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NAME_DB=faculty_hub_db
      - USER_DB=postgres
      - PASSWORD_DB=postgres
      - HOST_DB=postgres
      - PORT_DB=5432
    volumes:
      - .:/app
      - /app/node_modules


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: faculty_hub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
